### ISSUE TITLE
when import a new java model the model get 2 of "same imports" Mcreator 2023.3 - Plugin 1.4.2

### ISSUE THREAD

**Issue by Foxyas** [Spectrall368/Generator-1.18.2#2]
import net.minecraft.data.Main;
import net.minecraft.client.main.Main; 
the imports

**Comment by Foxyas** [comment]
i dont have 100% sure if is mcreator or is the blockbench the issue

**Comment by Spectrall368** [comment]
could you send me a workspace with the minimum reproducible to reproduce this issue?

**Comment by Foxyas** [comment]
ok i fix is the blockbench Sorry for waste your time

**Comment by Spectrall368** [comment]
Ok

**Comment by Foxyas** [comment]
really sorry ok

**Comment by Spectrall368** [comment]
No problem
